#!/usr/bin/env tsx
/**
 * Import data into Supabase database
 *
 * Usage:
 *   tsx scripts/import-data.ts
 *   npm run data:import
 *
 * This will run the SQL file generated by export-data.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { Pool } from 'pg';
import * as dotenv from 'dotenv';

dotenv.config();

const DATA_FILE = path.join(process.cwd(), 'supabase', 'seed', 'data.sql');

async function importData() {
  const dbUrl = process.env.SUPABASE_DB_URL;

  if (!dbUrl) {
    console.error('❌ Error: SUPABASE_DB_URL not found in .env file');
    console.error('   Please set it with your Supabase connection string');
    process.exit(1);
  }

  if (!fs.existsSync(DATA_FILE)) {
    console.error(`❌ Error: Data file not found: ${DATA_FILE}`);
    console.error('   Run "npm run data:export" first to generate the data file');
    process.exit(1);
  }

  console.log('🚀 Starting data import to Supabase...\n');

  const pool = new Pool({
    connectionString: dbUrl,
    ssl: {
      rejectUnauthorized: false
    }
  });

  try {
    // Test connection
    console.log('🔌 Connecting to database...');
    await pool.query('SELECT 1');
    console.log('✅ Connected!\n');

    // Read SQL file
    console.log('📖 Reading data file...');
    const sql = fs.readFileSync(DATA_FILE, 'utf8');
    const fileSize = (fs.statSync(DATA_FILE).size / 1024).toFixed(2);
    console.log(`✅ Loaded ${fileSize} KB\n`);

    // Count statements
    const statements = sql.split(';').filter(s => s.trim() && !s.trim().startsWith('--'));
    console.log(`📋 Found ${statements.length} SQL statements\n`);

    // Execute the SQL
    console.log('⏳ Importing data (this may take a while)...');
    console.log('');

    await pool.query(sql);

    console.log('✅ Import complete!\n');

    // Verify data
    console.log('🔍 Verifying import...');
    const tablesResult = await pool.query(`
      SELECT
        table_name,
        (SELECT COUNT(*) FROM information_schema.columns WHERE columns.table_name = tables.table_name) as columns,
        (xpath('/row/cnt/text()', query_to_xml(format('SELECT COUNT(*) as cnt FROM %I', table_name), false, true, '')))[1]::text::int as rows
      FROM information_schema.tables
      WHERE table_schema = 'public'
        AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `);

    let totalRows = 0;
    console.log('');
    tablesResult.rows.forEach(row => {
      const rowCount = row.rows || 0;
      totalRows += rowCount;
      const icon = rowCount === 0 ? '⚠️ ' : '✅';
      console.log(`   ${icon} ${row.table_name}: ${rowCount} rows`);
    });

    console.log('');
    console.log(`📊 Total rows imported: ${totalRows}`);
    console.log(`\n🎉 Data import successful!`);
    console.log(`\n📚 Next steps:`);
    console.log(`   1. Verify data in Supabase dashboard`);
    console.log(`   2. Query metrics: npm run metrics:all`);
    console.log(`   3. Generate additional data: npm run data:mock\n`);

  } catch (error: any) {
    console.error('\n❌ Import failed!');
    console.error('Error:', error.message);
    console.error('\n💡 Tips:');
    console.error('   - Make sure migrations are applied first: npm run deploy:supabase');
    console.error('   - Check your SUPABASE_DB_URL is correct');
    console.error('   - Verify you have write permissions\n');
    process.exit(1);
  } finally {
    await pool.end();
  }
}

importData();
